# Generated by Django 4.1.2 on 2022-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='dateCompleted',
            new_name='datecompleted',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
